import { useState } from "react";
import { ChevronDown, Eye, History } from "lucide-react";

import { cn } from "@/lib/utils";
import { ProposalPresentation, type ProposalRow } from "@/components/portal-proposal-presentation";

type Row = ProposalRow;

const ROWS: Row[] = [
  {
    client: "VZ Handyworks",
    business: "LLC",
    coverages: "Responsabilidad Civil General (GL), Propiedad Comercial (Commercial Property)",
    premium: "$4,198.34",
    status: "Pending Presentation",
  },
  {
    client: "SJ Grandma's Cleaning Services LLC.",
    business: "LLC",
    coverages:
      "Auto Personal, Inquilinos (Renters), Responsabilidad Civil General (GL), Otro / No Listado",
    premium: "$2,925.50",
    status: "Pending Presentation",
  },
  {
    client: "Patrimonia Legal LLC",
    business: "LLC",
    coverages:
      "Responsabilidad Cibernética (Cyber Liability), Responsabilidad Civil General (GL)",
    premium: "$3,678.00",
    status: "Pending Presentation",
  },
  {
    client: "Yanel Saenz",
    business: "",
    coverages: "Propietarios (Homeowners)",
    premium: "$3,182.13",
    status: "Accepted",
  },
  {
    client: "Yanel Saenz",
    business: "",
    coverages: "Auto Personal",
    premium: "$1,291.00",
    status: "Accepted",
  },
  {
    client: "GREEN GODDESS HOUSE OF HERBS",
    business: "LLC",
    coverages: "Business Owner's Policy (BOP)",
    premium: "$1,927.10",
    status: "Accepted",
  },
  {
    client: "La Esperanza Car Audio (DBA: Ledezma's Electronics)",
    business: "LLC",
    coverages:
      "Responsabilidad Civil General (GL), Propiedad Comercial (Commercial Property), Auto Comercial",
    premium: "$5,047.74",
    status: "Pending Presentation",
  },
  {
    client: "VZ Handyworks",
    business: "LLC",
    coverages: "Responsabilidad Civil General (GL), Propiedad Comercial (Commercial Property)",
    premium: "$2,258.48",
    status: "Pending Presentation",
  },
  {
    client: "AP Bookkeping",
    business: "LLC",
    coverages:
      "Errores y Omisiones (E&O) / Professional Liability, Responsabilidad Cibernética (Cyber Liability)",
    premium: "$1,508.00",
    status: "Pending Presentation",
  },
  {
    client: "GREEN GODDESS HOUSE OF HERBS",
    business: "LLC",
    coverages: "Responsabilidad Civil General (GL), Auto Comercial",
    premium: "$0.00",
    status: "Pending Presentation",
  },
  {
    client: "GREEN GODDESS HOUSE OF HERBS",
    business: "LLC",
    coverages: "Business Owner's Policy (BOP)",
    premium: "$1,861.92",
    status: "Pending Presentation",
  },
];

export function PortalProposals() {
  const [presenting, setPresenting] = useState<Row | null>(null);

  return (
    <div>
      <h1 className="font-serif text-3xl font-black tracking-tight text-[#16305C]">
        Ready Proposals
      </h1>
      <p className="mt-2 text-sm text-[#7A8494]">
        Proposals generated by Underwriting ready to be presented to your client.
      </p>

      <div className="mt-6 overflow-hidden rounded-2xl border border-[#EDE7DE] bg-white shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[1080px] border-collapse text-left">
            <thead>
              <tr className="bg-[#FAFAFB] align-top text-xs font-medium text-[#8A93A2]">
                <th className="px-6 py-4 font-medium">Client</th>
                <th className="px-4 py-4 font-medium">Business</th>
                <th className="px-4 py-4 font-medium">Coverages</th>
                <th className="px-4 py-4 font-medium leading-tight">
                  Total
                  <br />
                  Premium
                </th>
                <th className="px-4 py-4 font-medium">Status</th>
                <th className="px-6 py-4 text-right font-medium">Action</th>
              </tr>
            </thead>
            <tbody>
              {ROWS.map((r, i) => (
                <tr key={i} className="border-t border-[#EEF0F4]">
                  <td className="px-6 py-5 text-sm font-bold text-[#16305C]">{r.client}</td>
                  <td className="px-4 py-5 text-sm text-[#8A93A2]">{r.business}</td>
                  <td className="max-w-[470px] px-4 py-5 text-sm text-[#3F4A5C]">{r.coverages}</td>
                  <td className="px-4 py-5 text-sm font-bold text-[#0E8A54]">{r.premium}</td>
                  <td className="px-4 py-5">
                    <button
                      className={cn(
                        "inline-flex min-w-[160px] items-center justify-between gap-2 rounded-lg border px-3 py-2 text-xs font-bold",
                        r.status === "Accepted"
                          ? "border-[#B7E7CD] bg-[#E7F8EF] text-[#0E8A54]"
                          : "border-[#BFD6FF] bg-[#EAF2FF] text-[#1A56DB]",
                      )}
                    >
                      {r.status}
                      <ChevronDown className="size-3.5" />
                    </button>
                  </td>
                  <td className="px-6 py-5">
                    <div className="flex items-center justify-end gap-2">
                      <button className="grid size-9 shrink-0 place-items-center rounded-lg bg-[#F1F5F9] text-[#64748B] hover:bg-[#E2E8F0]">
                        <History className="size-4" />
                      </button>
                      <button
                        onClick={() => setPresenting(r)}
                        className="flex items-center gap-3 rounded-lg bg-[#16305C] px-4 py-2.5 text-sm font-semibold text-white hover:opacity-90"
                      >
                        <Eye className="size-4 shrink-0" />
                        <span className="text-right leading-tight">
                          View
                          <br />
                          Presentation
                        </span>
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
